version: '3'
services:
  k8s-node-descale:
    build:
      context: .
      args:
        - KUBE_VERSION
    environment:
      - MAX_AGE
      - MAX_NODES_COUNT
      - CHECK_PERIOD
      - DRY_RUN
    entrypoint: k8s-node-descale
